version: '3.8'

services:

  db:
    container_name: duplipensardb
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: BigBrother
      POSTGRES_PASSWORD: batata123
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
